### PR TITLE
Add require authorization plug

### PR DESCRIPTION
**Pull request by alishir**
name: ⚙ Improvement
about: add require authorization plug as discussed in #20 
labels: enhancement

### CODE REVIEW

**Comment by maennchen** [comment]
Thanks for the PR @alishir :heart: 

This plug duplicates the work of other plugs. Can we instead just see if the result of the validation plugs are present and send the response if not?

**Comment by alishir** [comment]
About the duplicate codes, I agree with you. However, if `RequireAuthorization` depends on `ValidateJwtToken`, we should chain three plugs together: `ExtractAuthorization`, `ValidateJwtToken`, and `RequireAuthorization`. I personally prefer chaining. If you're okay with it, I will update the PR.

**Comment by maennchen** [comment]
Awesome. Can you also add a tiny test?

**Comment by alishir** [comment]
Sure, I just added some test.

**Review by maennchen — APPROVED** [review]

**Pull request merged**
