### PR TITLE
Add client_context opts to Authorize and AuthorizationCallback plugs

### PR DESCRIPTION
**Pull request by MrYawe**
Sometimes you need to retrieve manually the client context without using a configuration worker.

### CODE REVIEW

**Comment by maennchen** [comment]
@MrYawe For what reason do you need to provide the context manually?

This implementation will not work. Plug evaluates arguments at compile time. Client contexts however, are not static.

**Comment by MrYawe** [comment]
@maennchen For a B2B SaaS with an Okta integration, we have one config (issuer / client_id / client_secret) per client.

We dynamically retrieve the `client_configuration` using the email address provided.

image
image

@maennchen Currently I can make it work like this in a Phoenix controller:
```elixir
def initiate(conn, %{"email" => email}) when is_binary(email) do
    case get_client_context(email) do
      {:ok, %ClientContext{} = client_context} ->
        opts = Authorize.init([client_context: client_context] ++ @base_config ++ @authorize_config)

        Authorize.call(conn, opts)

      error ->
        ...
    end
 end
 ```

**Comment by maennchen** [comment]
@MrYawe This syntax will unfortunately not work at all when using the plug as a plug.

There's additional concerns like the refresh mechanism on a new `kid`, that need to be handled properly.

OpenID knows the concept of a `Dynamic Relying Party`, in which case the consumer application can authenticate with multiple providers. (There's also parts of auto-discovery and dynamic client registration in there, which don't matter for this.) An implementation of that would require some kind of backend adapter, which persists / loads client contexts and could be extended with a custom strategy that implements your logic.

In this case, the plugs would be initialized with a client persistence backend module and not a provider id.

Example Behaviour:

```elixir
defmodule Oidcc.Plug.ClientPersistence do
  @callback get_client_context(conn :: Plug.Conn.t()) :: nil | Oidcc.ClientContext.t()
  @callback refresh_jwks(context :: Oidcc.ClientContext.t()) :: {:ok, JOSE.JWK.t()} | {:error, term()}
  @optional_callbacks refresh_jwks: 1
end
```

**Comment by MrYawe** [comment]
@maennchen Thanks for the feedback. I'll try to look at it next week

**Comment by maennchen** [comment]
@MrYawe I'm going to close the PR for now. Feel free to reopen if you want to pursue the stuff discussed above.
In any case: Thanks for the effort :heart:

**Pull request closed without merging**
